feat(MCPE-4354): Add `handoverControlsToSco` property
extenda/hiiretail-json-schema-registry pull request #168
Opened 2024-10-23 10:46 UTC by ivolcov

2024-10-24 11:59 UTC, vicsvet approved these changes

2024-10-25 09:26 UTC, khamooshi requested changes

2024-10-25 09:26 UTC, khamooshi commented on customer-config/scan-and-go/sng.settings.v1.json
> +      "description": "When true, Scan&Go will handover controls to SCO",
When set to true, Scan&Go bypasses basket controls, assuming they are managed externally.

2024-10-28 08:32 UTC, khamooshi approved these changes

2024-10-28 08:37 UTC, merged