feat(MCPE-3601): Add scannerInactiveDaysBeforeRemoval property
extenda/hiiretail-json-schema-registry pull request #173
Opened 2024-10-31 13:33 UTC by vicsvet

2024-11-01 09:35 UTC, VisVladimir approved these changes

2024-11-04 11:03 UTC, khamooshi requested changes

2024-11-04 11:03 UTC, khamooshi commented on customer-config/scan-and-go/sng.device-api-settings.v1.json
> +    "scannerInactiveDaysBeforeRemoval": {
please rename to `hhsInactiveDaysBeforeRemoval` to have consistence naming considering the other setting name which is `hhsMinimumBatteryLevelRequiredToRelease`

2024-11-04 11:03 UTC, khamooshi commented on customer-config/scan-and-go/sng.device-api-settings.v1.json
> +      "description": "The amount of days after which inactive handheld scanner is removed. Default value 0: scanners won't be removed."
Number of days after which an inactive handheld scanner is removed. The default is set to 90 days.

2024-11-04 11:03 UTC, khamooshi commented on customer-config/scan-and-go/sng.device-api-settings.v1.json
> +      "description": "The amount of days after which inactive handheld scanner is removed. Default value 0: scanners won't be removed."
Default value should not be zero, it should be 90 days.

2024-11-05 08:59 UTC, khamooshi commented on customer-config/scan-and-go/sng.device-api-settings.v1.json
> +      "description": "The amount of days after which inactive handheld scanner is removed. Default value: 90"
Would you change the description to 
"Number of days after which an inactive handheld scanner is removed. The default is set to 90 days."

and please merge after this change if someone approves

2024-11-05 08:59 UTC, khamooshi approved these changes

2024-11-05 10:50 UTC, merged